# Generated by Django 5.0.6 on 2024-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_page_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
